### ISSUE TITLE
Add warp-sync `zombienet` test with validators

### ISSUE THREAD

**Issue by michalkucharczyk** [paritytech/substrate#12769]
This is followup of #11471.

The [warp-sync test](https://github.com/paritytech/substrate/blob/mku-basic-warp-sync-test/zombienet/0001-basic-warp-sync/0001-test-warp-sync.toml) for full-nodes was implemented in https://github.com/paritytech/substrate/pull/12675.

The [warp-sync test](https://github.com/paritytech/substrate/blob/mku-warp-sync-ci-test/zombienet/0001-basic-warp-sync/0001-test-warp-sync.toml) with validators should also be added. The initial try was taken in #12751, however the test is failing with following errors:
```
2022-11-18 17:05:10.577  WARN tokio-runtime-worker sync: 💔 Verification failed for block 0xf0756734abbabde16cae212d5f238994707d69fa2fe7e4d095a281638b2998fc received from peer: 12D3KooWRkZhiRhsqmrQ28rt73K7V3aCBpqKrLGSXmZ99PTcTZby, "Could not fetch epoch at 0x5448eda4b7963ee85d28ea523149317dc39ce41173e198126b7ba67b7e123854"
```
or
```
2022-11-18 16:57:55.224  WARN tokio-runtime-worker sync: 💔 Verification failed for block 0x105866ce153d80fff9d67ea804cd43543bffd1e66c0714e40a79ad6c9f8d0008 received from peer: 12D3KooWRkZhiRhsqmrQ28rt73K7V3aCBpqKrLGSXmZ99PTcTZby, "VRF verification failed: EquationFalse"
```

The warp-sync test for validators could be added to #11727. More sophisticated scenario could be tested e.g. sync-warp validators and check if they can produce blocks.

**Comment by bkchr** [comment]
> 2022-11-18 16:57:55.224  WARN tokio-runtime-worker sync: 💔 Verification failed for block 0x105866ce153d80fff9d67ea804cd43543bffd1e66c0714e40a79ad6c9f8d0008 received from peer: 12D3KooWRkZhiRhsqmrQ28rt73K7V3aCBpqKrLGSXmZ99PTcTZby, "VRF verification failed: EquationFalse"

But this should be solved now?

**Comment by michalkucharczyk** [comment]
Should be, but test is still not passing: https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2084982
([PR](https://github.com/paritytech/substrate/pull/12751) with recent master merged, [test toml](https://github.com/paritytech/substrate/blob/mku-warp-sync-ci-test/zombienet/0001-basic-warp-sync/0001-test-warp-sync.toml))

**Comment by michalkucharczyk** [comment]
Root cause: https://github.com/paritytech/substrate/pull/12751#issuecomment-1328032781
