### ISSUE TITLE
sp-core `full_crypto` is no_std incompatible

### ISSUE THREAD

**Issue by Slesarew** [paritytech/substrate#12793]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

When building for `no_std` targets, `sp-core` dependency fails due to issue with [libsecp256k1](https://github.com/paritytech/libsecp256k1)

```
$cargo build --target=thumbv7m-none-eabi

<truncated>

error[E0463]: can't find crate for `std`
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/subtle-2.4.1/src/lib.rs:88:1
   |
88 | extern crate std;
   | ^^^^^^^^^^^^^^^^^ can't find crate
   |
   = note: the `thumbv7m-none-eabi` target may not support the standard library
   = help: consider building the standard library from source with `cargo build -Zbuild-std`


```

See more details and proposed fix https://github.com/paritytech/libsecp256k1/pull/146

### Steps to reproduce

1. Install appropriate targets
2. `$cargo generate --git https://github.com/rust-embedded/cortex-m-quickstart`
3. give test project a name, cd
4. add to Cargo.toml `sp-core = {version = "7.0.0", default-features = false, features = ["full_crypto"]}` dependency
5. `$cargo build --target=thumbv7m-none-eabi`

**Comment by bkchr** [comment]
There was recently an issue around `no_std` incompatibility. Which was solved? https://github.com/paritytech/substrate/issues/12225

Maybe the problem is the target architecture.

**Comment by Slesarew** [comment]
Looks similar, but this time it's ECDSA, different crypto and different crate. Issue you refer to is about `ed25519-zebra` crate, while this is `libsecp256k1` crate, and it still persists even in 7.0.0

With a tweak proposed above it builds nicely, should be a simple fix since the lib is also owned by Parity.

**Comment by bkchr** [comment]
Ahh the problem is that `libsecp256k1` is pulled in `build-dependencies`.

The solution to your problem is to add:
```
[workspace]
resolver = "2"
```

in your workspace `Cargo.toml`.

**Comment by Slesarew** [comment]
It does work indeed, did not notice that `generate` script still uses 2018 rust version. Setting rust edition to 2021 seems even better here.
