### ISSUE TITLE
Cryptographic authentication of validators' session keys in network

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#271]
Using an additional signature using validator session keys on a derived value from the underlying DH shared secret of the network connection.

cc @burdges and @tomaka

**Comment by rphmeier** [comment]
(for libp2p we would want a function of some kind like `connection.derive_from_shared_secret("constant string") -> H256` which does a cryptographic hash of the shared secret and concatenation of the constant string.

**Comment by burdges** [comment]
s/and concatenation of/concatenated with/

It's unclear if there is a reasonable way to extract session key information from libp2p, but even if we do so it makes auditing hard because the security of validators binding to sessions now reduces to the transport security.

I think GNUNet addresses this with its CADET layer that maintains connection state between nodes independent from the underlying transport layer.  We could do a much simpler things, but we should asses if adding a CADET like layer to libp2p would solve a wider array of problems.

**Comment by rphmeier** [comment]
yes, relying purely on the transport is also not as agnostic as I'd like. The overhead of doing another DH agreement or similar on top will not be prohibitive, as we need a handshake message for other reasons anyway.

Collators will also need to do this authentication with validators.

**Comment by rphmeier** [comment]
Authentication of session keys should also be limited only to when they change.

**Comment by burdges** [comment]
In principle, some relay circuit might straddle multiple lower level connections, thanks to doing its own encryption.  I'm doubtful if that's worth the engineering work, but it's possible and CADET does that, which improves its forward security properties thanks to ratcheting.  I doubt the forward security properties matter so much to us, but maybe for other libp2p users.

**Comment by gavofyork** [comment]
@rphmeier is this required for this milestone?

**Comment by gavofyork** [comment]
Any updates here?

**Comment by tomaka** [comment]
I think the idea was abandoned?

**Comment by burdges** [comment]
We need authentication from the session key of course, but I read active issues as trying to find a better way to do so, using the built in authentication mechanisms of things like Noise.  I think this is exactly what @tomaka just said.

**Comment by DemiMarie-parity** [comment]
@burdges I agree.  @rphmeier should this be closed?

**Comment by rphmeier** [comment]
Nope, should stay open.

**Comment by DemiMarie-parity** [comment]
@rphmeier I take it that Polkadot is no longer blocking on this?

I believe that this feature should be added to libp2p.

**Comment by rphmeier** [comment]
Polkadot definitely needs this and will block on it after PoC-4. Would be good to figure out how to do it before then.

**Comment by burdges** [comment]
A priori, one should fix this inside libp2p because it's basic networking functionality.  

We've two cryptography routes for libp2p:   Noise wants X25519 keys.  TLS 1.3 wants some certificate that wraps various key types, like Ed25519, RSA, etc.

In both cases, some handshakes permit transferring some data before authentication finishes, maybe quite a bit in some cases.  I don  Noise supports many variants with different final authentication states.  I donno if you care about either.

If you know in advance to whom you're talking, then you could give libp2p an X25519 or Ed25519 key. If you only learn their identity later, then afaik any handshake we'd use sends the authenticating key across, but then libp2p ask its caller to authenticate the supplied key, so you look up the controller account key and session key record using the supplied X25519 or Ed25519 key.  

If the Noise or TLS 1.3 library does not support sending data before authentication finishes, then maybe this request to the caller comes in the form of some function returning, but probably not since everything is asynchronous anyways.  It's possible some TLS 1.3 libraries have no request authentication function, only doing authentication from CAs.  We should either add such a function or use a different TLS 1.3 library in such cases.

**Comment by tomaka** [comment]
I still don't have any clear idea of the problem that we're trying to solve, as I fail to see why `if expected_network_key != actual_network_key { return Err() }` is not enough.

**Comment by DemiMarie-parity** [comment]
@tomaka We need to ensure that a MITM cannot fool us.  That is, we need our peer to sign something known only to us and the peer.

**Comment by DemiMarie-parity** [comment]
@gavofyork @rphmeier could @tomaka’s idea actually be enough?

**Comment by rphmeier** [comment]
Sure, provided you actually have a good way to get `expected_network_key`. That's what #3247 is aiming to do.

**Comment by rphmeier** [comment]
(Substrate's "Authority Discovery" feature should alleviate this)

**Comment by burdges** [comment]
There are two separate problems here: 

I think the RPC by @bkchr now handles signing actual session keys by controller account keys, meaning it provides "cryptographic authentication of validators' session keys in network". 

We've mostly discussed authenticating transport keys in this thread, which now presumably includes the transport keys for sentry nodes. 

I heard @DemiMarie-parity wants to improve one of the QUIC implementations, which normally means TLS 1.3, and thus certificates that support Ed25519.  Any validator would certify their sentry nodes and their own transport keys using some TransportAuth session key, for which we might simply reuse the ImOnline session key.

cc @infinity0

**Comment by bkchr** [comment]
We have now signed authority discovery keys, that should solve this issue.
